name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the book
      run: |
        curl -sL https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar zx
        ./mdbook build
    - name: Deploy
      if: github.repository == 'sgrif/diesel.rs-website' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: book # The folder the action should deploy.
        clean: true
        clean-exclude: |
          CNAME
